services:
  server:
    build:
      context: .
    image: minecraft-bedrock
    environment:
      EULA_ACCEPT: "true"
      CFG_SERVER_NAME: test_server
      CFG_GAMEMODE: creative
      CFG_LEVEL_NAME: test_server
    ports:
      - '8080:8080'
      - '19132:19132/udp'
    # volumes:
    #   - $PWD/worlds:/opt/minecraft/worlds
