# Default values for minecraft-bedrock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/jsandas/minecraft-bedrock
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # NodePort or LoadBalancer are the recommended service types
  type: NodePort
  port: 19132
  nodePort: 32132
  # type: LoadBalancer
  # loadBalancerIP:
  # loadBalancerClass:

hostNetwork: false

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  annotations: {}
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  accessMode: ReadWriteOnce
  size: 8Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  # exec:
  #   command:
  #     - mc-monitor 
  #     - status-bedrock 
  #     - --host
  #     - 127.0.0.1
  #     - --port
  #     - "{{ .Values.service.port }}"
readinessProbe:
  # exec:
  #   command:
  #     - mc-monitor 
  #     - status-bedrock 
  #     - --host
  #     - 127.0.0.1
  #     - --port
  #     - "{{ .Values.service.port }}"

nodeSelector: {}

tolerations: []

affinity: {}

minecraft:
  # Environmental variables
  env:
    # Must accept the Minecraft EULA and Microsoft Privacy Policy"
    # Links:"
    #   https://www.minecraft.net/en-us/terms"
    #   https://privacy.microsoft.com/en-us/privacystatement"
    EULA_ACCEPT: "false"
  # Config keys match server.properties execept hyphens (-) need to be replaced with underscores (_) 
  # while upper-case is optional for keys. Example: server-name = SERVER_NAME
  # Config values cannot have space as they will not be set properly in the properties file
  config:
    SERVER_NAME: test_server
    GAMEMODE: creative
    LEVEL_NAME: test_server
