apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}
  labels:
    {{- include "minecraft-bedrock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  loadBalancerClass: {{ default "" .Values.service.loadBalancerClass }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: minecraft-udp
      protocol: UDP
      name: minecraft-udp
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.service.nodePort}}
      {{- end }}
  selector:
    {{- include "minecraft-bedrock.selectorLabels" . | nindent 4 }}
