name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "MC_VER=$(cat Dockerfile | grep MC_VER= | awk -F "=" '{print $2}')" >> $GITHUB_ENV

      - name: Run integration tests
        run: |
          docker compose build --no-cache
          docker compose up -d
          sleep 15; docker compose exec -it server bash -c "mc-monitor status-bedrock --host 127.0.0.1" | grep ${MC_VER}
      
      - run: |
          docker compose down || true