name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "MC_VER=$(cat Dockerfile | grep MC_VER= | awk -F "=" '{print $2}')" >> $GITHUB_ENV

      - name: Build and run server
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Run integration tests
        run: |
          ./mccli check_server
      
      - run: |
          docker compose down || true