name: Version Check

on:
  schedule:
    - cron: "7 */4 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env Vars
        run: bash version_check.sh
